name: Prepare release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: patch
        type: string
      release-type:
        type: choice
        description: Packages
        options:
          - '@tutorialkit/* and create-tutorial'
          - tutorialkit CLI

jobs:
  prepare_release:
    name: Prepare release PR
    if: ${{ contains(inputs.release-type, '@tutorialkit') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: pnpm/action-setup@v4

      - name: Install & Build
        run: |
          pnpm install
          pnpm build

      - name: Bump versions
        run: >
          pnpm --recursive
          --filter "@tutorialkit/*"
          --filter create-tutorial
          exec npm version --no-git-tag-version --allow-same-version ${{ inputs.version }}

      - name: Generage changelog
        run: |
          pnpm run changelog
          git checkout ./packages/cli

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: bump ${{ inputs.release-type }} version to ${{ inputs.version }}'
          title: 'chore: bump ${{ inputs.release-type }} version to ${{ inputs.version }}'
          body: 'Bump packages to version ${{ inputs.version }}'
          #reviewers: SamVerschueren,d3lm,Nemikolh,AriPerkkio
          reviewers: AriPerkkio
          branch: chore/bump-version

  prepare_release_CLI:
    name: Prepare release PR CLI
    if: ${{ contains(inputs.release-type, 'tutorialkit CLI') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: pnpm/action-setup@v4

      - name: Install & Build
        run: |
          pnpm install
          pnpm build

      - name: Bump version
        run: >
          pnpm --recursive
          --filter tutorialkit
          exec npm version --no-git-tag-version --allow-same-version ${{ inputs.version }}

      - name: Update template's versions
        working-directory: ./packages/template
        run: >
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
            pkg.dependencies['@tutorialkit/components-react'] = '${{ inputs.version }}';
            pkg.devDependencies['@tutorialkit/astro'] = '${{ inputs.version }}';
            pkg.devDependencies['@tutorialkit/types'] = '${{ inputs.version }}';
          "

      - name: Update template's lockfiles
        working-directory: ./packages/template
        run: |
          mkdir lockfiles
          rm -rf node_modules
          npm install
          mv package-lock.json lockfiles/
          rm -rf node_modules
          pnpm i
          mv pnpm-lock.yaml lockfiles/
          rm -rf node_modules
          echo "TODO Yarn"

      - name: Generage changelog
        run: |
          pnpm run changelog
          git add ./packages/cli
          git reset ./packages

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: bump ${{ inputs.release-type }} version to ${{ inputs.version }}'
          title: 'chore: bump ${{ inputs.release-type }} version to ${{ inputs.version }}'
          body: 'Bump packages to version ${{ inputs.version }}'
          #reviewers: SamVerschueren,d3lm,Nemikolh,AriPerkkio
          reviewers: AriPerkkio
          branch: chore/bump-version
