name: Publish release

on:
  push:
    branches:
      - main

jobs:
  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    # Note: `prepare-release.yaml` sets this commit message
    if: ${{ contains(github.event.head_commit.message, 'release @tutorialkit packages') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-and-build

      # Sets steps.resolve-release-version.outputs.version
      - uses: ./.github/actions/resolve-release-version
        id: resolve-release-version

      # TODO: Remove --dry-run
      - name: Publish to npm
        run: >
          pnpm --recursive
          --filter "@tutorialkit/*"
          --filter create-tutorial
          exec pnpm publish --provenance --dry-run
        env:
          NODE_AUTH_TOKEN: fail-and-prevent-release
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create and push git tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git tag v${{ steps.resolve-release-version.outputs.version }}
          git push origin v${{ steps.resolve-release-version.outputs.version }}
